table Dim_Date
	lineageTag: fe808c2c-b5e9-40bc-9477-39e147e78ae9

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 44def99f-2a0f-4594-8296-089df994469f
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 439585d4-85e2-4258-894c-6c21c41fa4fc
			defaultHierarchy: LocalDateTable_f94da17b-026f-47d1-8153-e2fe45439a36.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: f406a347-397f-48b9-88d7-e153bb8346a4
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: b825dd1d-cb9e-42be-9f5f-310e299657dc
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: c490e356-58ce-4a48-b9ea-e6e79a75f6cb
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 07d0fe61-a41e-43a4-bb02-887a804de2bb
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
				    Source = Fact_Sales,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"date"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates",{{"date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([date]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([date]), type text),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Month Name", "Day", each Date.Day([date]), Int64.Type)
				in
				    #"Inserted Day"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

