table Fact_Sales
	lineageTag: 912b8acb-bcd7-4501-8945-72877e10a7f2

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 362ffcf7-f0b5-4659-94f8-c06d9e9fbf82
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3e9a83ba-0589-47b5-b0cb-6309ca1d7494
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: e4ed8829-43c1-45e9-b008-7211014ae698
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 15562d48-a8dd-486f-8e58-21ef97a72697
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: eec98766-99e2-4396-8fbf-b24e174892c1
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 4b3286b4-dab6-4b13-ac31-9b2700984ea7
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 9d6144a4-2cb8-4fdb-be23-fe3712c84f34
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: a10225ed-200d-4b4c-a3fd-a6495ecfa3ce
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 121c0fae-66a9-42b5-bfd0-cc4540ed3cf3
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Month-over-Month Sales Growth %' =
		VAR CurrentMonthSales = SUM(Fact_Sales[sales_amount])
		VAR PreviousMonthSales =
			CALCULATE(
				SUM(Fact_Sales[sales_amount]),
				PREVIOUSMONTH(Dim_Date[date])
			)
		RETURN
			DIVIDE(CurrentMonthSales - PreviousMonthSales, PreviousMonthSales)
		formatString: 0.00%;-0.00%;-

	measure 'Cumulative Sales' =
		VAR CurrentDate = MAX(Dim_Date[date])
		RETURN
			CALCULATE(
				SUM(Fact_Sales[sales_amount]),
				FILTER(
					ALL(Dim_Date[date]),
					Dim_Date[date] <= CurrentDate
				)
			)

	measure 'Item Sales Rank' =
		RANKX(
			ALL(Fact_Sales[item]),
			CALCULATE(SUM(Fact_Sales[sales_amount])),
			,
			DESC,
			Dense
		)

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Business Intelligence Assignment\Lab miniproject brew metrics\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

